import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:provider/provider.dart';
import '../../../shared/services/room_service.dart';
import '../../../shared/widgets/common_app_bar.dart';
import '../../../shared/providers/theme_provider.dart';

class ScannerPage extends StatefulWidget {
  final GlobalKey<ScaffoldState>? scaffoldKey;

  const ScannerPage({super.key, this.scaffoldKey});

  @override
  State<ScannerPage> createState() => _ScannerPageState();
}

class _ScannerPageState extends State<ScannerPage> with WidgetsBindingObserver {
  final MobileScannerController cameraController = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
    facing: CameraFacing.back,
  );
  
  bool _isFlashOn = false;
  String? _scannedCode;
  bool _isValidating = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    cameraController.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (!cameraController.value.isInitialized) {
      return;
    }
    
    switch (state) {
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
        return;
      case AppLifecycleState.resumed:
        cameraController.start();
        return;
      case AppLifecycleState.inactive:
        cameraController.stop();
        return;
    }
  }

  void _toggleFlash() {
    setState(() {
      _isFlashOn = !_isFlashOn;
    });
    cameraController.toggleTorch();
  }

  void _handleBarcode(BarcodeCapture capture) {
    if (_isValidating) return;
    final List<Barcode> barcodes = capture.barcodes;
    if (barcodes.isNotEmpty) {
      final String? code = barcodes.first.rawValue;
      if (code != null && code != _scannedCode) {
        setState(() {
          _scannedCode = code;
        });
        _validateAndNavigate(code);
      }
    }
  }

  void _validateAndNavigate(String code) async {
    setState(() => _isValidating = true);
    try {
      // Look up the room by QR code data in the database
      final room = await RoomService.fetchByQRCode(code);
      if (!mounted) return;

      if (room != null) {
        // Valid QR code — navigate to verification page with room data
        await Navigator.pushNamed(
          context,
          '/room-verification',
          arguments: {
            'roomId': room.id,
            'room': room,
          },
        );
      } else {
        // Invalid QR code — show error
        _showInvalidQRCodeDialog();
      }
    } catch (_) {
      if (mounted) _showInvalidQRCodeDialog();
    }
    if (mounted) {
      setState(() {
        _scannedCode = null;
        _isValidating = false;
      });
    }
  }

  void _showInvalidQRCodeDialog() {
    showDialog(
      context: context,
      builder: (context) => Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                width: 64,
                height: 64,
                decoration: BoxDecoration(
                  color: Colors.red.shade50,
                  shape: BoxShape.circle,
                ),
                child: Icon(Icons.error_outline, color: Colors.red.shade600, size: 36),
              ),
              const SizedBox(height: 20),
              const Text(
                'Invalid QR Code',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.black87),
              ),
              const SizedBox(height: 8),
              Text(
                'This QR code is not recognized. Please scan a valid room QR code generated by the admin.',
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 13, color: Colors.grey.shade600, height: 1.4),
              ),
              const SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: () => Navigator.pop(context),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF4169E1),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 12),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                  child: const Text('Try Again', style: TextStyle(fontWeight: FontWeight.w600)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _enterManually() {
    Navigator.pushNamed(context, '/manual-room-entry');
  }

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, _) {
        return Scaffold(
          backgroundColor: themeProvider.backgroundColor,
          appBar: CommonAppBar(
            roleText: 'STUDENT/TEACHER',
            primaryColor: themeProvider.primaryColor,
            onMenuPressed: () => widget.scaffoldKey?.currentState?.openDrawer(),
          ),
          body: Column(
            children: [
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    children: [
                      const SizedBox(height: 20),
                      // QR Scanner View
                      Expanded(
                        child: Container(
                          decoration: BoxDecoration(
                            border: Border.all(
                              color: themeProvider.primaryColor,
                              width: 3,
                              strokeAlign: BorderSide.strokeAlignInside,
                            ),
                            borderRadius: BorderRadius.circular(16),
                          ),
                          child: ClipRRect(
                            borderRadius: BorderRadius.circular(13),
                            child: Stack(
                              children: [
                                MobileScanner(
                                  controller: cameraController,
                                  onDetect: _handleBarcode,
                                ),
                                // Dashed border overlay
                                CustomPaint(
                                  painter: DashedBorderPainter(
                                    color: themeProvider.primaryColor,
                                    strokeWidth: 3,
                                    dashWidth: 10,
                                    dashSpace: 5,
                                  ),
                                  child: Container(),
                                ),
                                // Corner brackets
                                Positioned(
                                  top: 20,
                                  left: 20,
                                  child: _buildCornerBracket(
                                    isTop: true,
                                    isLeft: true,
                                    color: themeProvider.primaryColor,
                                  ),
                                ),
                                Positioned(
                                  top: 20,
                                  right: 20,
                                  child: _buildCornerBracket(
                                    isTop: true,
                                    isLeft: false,
                                    color: themeProvider.primaryColor,
                                  ),
                                ),
                                Positioned(
                                  bottom: 20,
                                  left: 20,
                                  child: _buildCornerBracket(
                                    isTop: false,
                                    isLeft: true,
                                    color: themeProvider.primaryColor,
                                  ),
                                ),
                                Positioned(
                                  bottom: 20,
                                  right: 20,
                                  child: _buildCornerBracket(
                                    isTop: false,
                                    isLeft: false,
                                    color: themeProvider.primaryColor,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 16),
                      // Instruction text
                      Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          border: Border.all(
                            color: themeProvider.primaryColor,
                            width: 2,
                            style: BorderStyle.solid,
                          ),
                          borderRadius: BorderRadius.circular(8),
                          color: themeProvider.cardColor,
                        ),
                        child: Text(
                          'Point your camera at the QR code of the room',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 13,
                            color: themeProvider.textColor,
                            height: 1.4,
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),
                      // Enter Manually Button
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton.icon(
                          onPressed: _enterManually,
                          icon: const Icon(Icons.edit_outlined, size: 20),
                          label: const Text(
                            'Enter Manually',
                            style: TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: themeProvider.primaryColor,
                            foregroundColor: Colors.white,
                            padding: const EdgeInsets.symmetric(vertical: 16),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            elevation: 0,
                          ),
                        ),
                      ),
                      const SizedBox(height: 16),
                      // Flash Toggle
                      InkWell(
                        onTap: _toggleFlash,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(
                              _isFlashOn ? Icons.flash_on : Icons.flash_off,
                              color: themeProvider.primaryColor,
                              size: 20,
                            ),
                            const SizedBox(width: 8),
                            Text(
                              _isFlashOn ? 'Flash On' : 'Flash Off',
                              style: TextStyle(
                                fontSize: 14,
                                fontWeight: FontWeight.w600,
                                color: themeProvider.primaryColor,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 20),
                    ],
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildCornerBracket({required bool isTop, required bool isLeft, required Color color}) {
    return Container(
      width: 40,
      height: 40,
      decoration: BoxDecoration(
        border: Border(
          top: isTop
              ? BorderSide(color: color, width: 4)
              : BorderSide.none,
          bottom: !isTop
              ? BorderSide(color: color, width: 4)
              : BorderSide.none,
          left: isLeft
              ? BorderSide(color: color, width: 4)
              : BorderSide.none,
          right: !isLeft
              ? BorderSide(color: color, width: 4)
              : BorderSide.none,
        ),
      ),
    );
  }
}

// Custom painter for dashed border
class DashedBorderPainter extends CustomPainter {
  final Color color;
  final double strokeWidth;
  final double dashWidth;
  final double dashSpace;

  DashedBorderPainter({
    required this.color,
    required this.strokeWidth,
    required this.dashWidth,
    required this.dashSpace,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;

    final path = Path();
    double startX = 0;
    
    // Top border
    while (startX < size.width) {
      path.moveTo(startX, 0);
      path.lineTo(startX + dashWidth, 0);
      startX += dashWidth + dashSpace;
    }
    
    // Right border
    double startY = 0;
    while (startY < size.height) {
      path.moveTo(size.width, startY);
      path.lineTo(size.width, startY + dashWidth);
      startY += dashWidth + dashSpace;
    }
    
    // Bottom border
    startX = size.width;
    while (startX > 0) {
      path.moveTo(startX, size.height);
      path.lineTo(startX - dashWidth, size.height);
      startX -= dashWidth + dashSpace;
    }
    
    // Left border
    startY = size.height;
    while (startY > 0) {
      path.moveTo(0, startY);
      path.lineTo(0, startY - dashWidth);
      startY -= dashWidth + dashSpace;
    }

    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}
