import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:provider/provider.dart';
import '../../../authentication/services/auth_service.dart';
import '../../../shared/models/room_model.dart';
import '../../../shared/services/room_service.dart';
import '../../../shared/utils/qr_decoder_helper.dart';
import '../../../shared/widgets/already_reported_dialog.dart';
import '../../../shared/widgets/department_mismatch_dialog.dart';
import '../teacher_nav_controller.dart';
import '../../admin/shared/admin_styles.dart';

class TeacherScannerWeb extends StatefulWidget {
  const TeacherScannerWeb({super.key});

  @override
  State<TeacherScannerWeb> createState() => _TeacherScannerWebState();
}

class _TeacherScannerWebState extends State<TeacherScannerWeb> {
  final TextEditingController _codeController = TextEditingController();
  bool _isVerifying = false;
  bool _isScanning = false;
  bool _isUploading = false;
  String? _error;
  Room? _verifiedRoom;
  Uint8List? _uploadedImageBytes;

  @override
  void initState() {
    super.initState();
    _codeController.addListener(_forceUppercase);
  }

  void _forceUppercase() {
    final text = _codeController.text;
    final upper = text.toUpperCase();
    if (text != upper) {
      _codeController.value = _codeController.value.copyWith(
        text: upper,
        selection: TextSelection.collapsed(offset: upper.length),
      );
    }
  }

  @override
  void dispose() {
    _codeController.removeListener(_forceUppercase);
    _codeController.dispose();
    super.dispose();
  }

  Future<void> _verifyRoom({String? directCode}) async {
    final code = (directCode ?? _codeController.text).trim().toUpperCase();
    if (code.isEmpty) return;

    setState(() {
      _isVerifying = true;
      _error = null;
    });

    try {
      final room = await RoomService.findRoomByScannedCode(code);
      if (!mounted) return;

      if (room != null) {
        final user = context.read<AuthService>().currentUser;
        if (isRoomOfOtherDepartment(user: user, room: room)) {
          setState(() {
            _isVerifying = false;
            _isScanning = false;
          });
          await showDepartmentMismatchDialog(
            context: context,
            roomCode: room.code,
            roomName: room.name,
            roomDepartment: room.department,
            userDepartment: user?.department,
          );
          _codeController.clear();
          return;
        }

        // Check if room is already reported
        final s = room.status.toLowerCase().trim();
        final isReported = s != 'available' && s != 'reserved';
        if (isReported) {
          final proceed = await showAlreadyReportedDialog(
            context: context,
            room: room,
          );
          if (!proceed || !mounted) {
            setState(() {
              _isVerifying = false;
            });
            return;
          }
        }

        // Show the Room Verification confirmation view matching mobile app behavior
        setState(() {
          _isScanning = false;
          _verifiedRoom = room;
          _error = null;
        });
      } else {
        setState(() {
          _error = 'Room not found. Please scan or enter a valid room QR code generated by the admin.';
        });
        _showInvalidQRDialog('This QR code or room code is not recognized as a registered campus room in PSU E-Ayos.');
      }
    } catch (e) {
      if (mounted) {
        setState(() => _error = 'An error occurred while verifying the room. Please try again.');
      }
    } finally {
      if (mounted) setState(() => _isVerifying = false);
    }
  }

  Future<void> _uploadAndDecodeQr() async {
    setState(() {
      _isUploading = true;
      _error = null;
    });

    try {
      final result = await QrDecoderHelper.pickAndDecodeQr();
      if (!mounted) return;

      if (result == null || !result.hasCode) {
        setState(() {
          _isUploading = false;
          _uploadedImageBytes = result?.imageBytes;
        });
        _showInvalidQRDialog('No QR code was detected in the uploaded image. Please make sure the image is clear and contains a valid QR code.');
        return;
      }

      setState(() {
        _uploadedImageBytes = result.imageBytes;
      });

      final decodedCode = result.code!;
      _codeController.text = decodedCode.toUpperCase();
      await _verifyRoom(directCode: decodedCode);
    } catch (e) {
      if (mounted) {
        _showInvalidQRDialog('Could not decode QR code from the selected image. Please try another image.');
      }
    } finally {
      if (mounted) {
        setState(() => _isUploading = false);
      }
    }
  }

  void _proceedToForm() {
    if (_verifiedRoom == null) return;
    final room = _verifiedRoom!;

    TeacherNavController.of(context)?.navigateTo(
      11,
      roomId: room.code.isNotEmpty ? room.code : room.id,
      roomName: room.name,
      buildingName: room.building,
      floor: room.floor,
      departmentName: room.department,
    );

    // Reset verification state for next time
    setState(() {
      _verifiedRoom = null;
      _uploadedImageBytes = null;
      _codeController.clear();
    });
  }

  void _showInvalidQRDialog(String message) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: const Row(
          children: [
            Icon(Icons.error_outline_rounded, color: Colors.red, size: 26),
            SizedBox(width: 10),
            Text('Invalid Room QR Code', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 17)),
          ],
        ),
        content: Text(
          message,
          style: const TextStyle(fontSize: 14, height: 1.4, color: Color(0xFF4B5563)),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            style: TextButton.styleFrom(foregroundColor: AdminStyles.primary),
            child: const Text('Try Again', style: TextStyle(fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );
  }

  Color _statusColor(String status) {
    switch (status.toLowerCase().trim()) {
      case 'available':
        return const Color(0xFF10B981);
      case 'reserved':
        return const Color(0xFFF59E0B);
      case 'pending':
      case 'submitted':
      case 'under review':
        return const Color(0xFFF59E0B);
      case 'approved':
      case 'confirmed':
      case 'assigned':
      case 'accepted':
        return const Color(0xFF3B82F6);
      case 'in progress':
      case 'in_progress':
        return const Color(0xFF8B5CF6);
      case 'inspection':
      case 'pre-inspection':
      case 'post repair':
      case 'post-repair':
        return const Color(0xFF06B6D4);
      case 'rework':
      case 'maintenance':
        return const Color(0xFFEF4444);
      default:
        return const Color(0xFFF59E0B);
    }
  }

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final bool isNarrow = screenWidth < 500;

    return Container(
      color: AdminStyles.bg,
      child: Center(
        child: SingleChildScrollView(
          child: Container(
            constraints: const BoxConstraints(maxWidth: 520),
            margin: EdgeInsets.symmetric(
              horizontal: isNarrow ? 16 : 24,
              vertical: isNarrow ? 16 : 40,
            ),
            padding: EdgeInsets.all(isNarrow ? 20 : 36),
            decoration: AdminStyles.cardDecoration(hasShadow: true),
            child: _verifiedRoom != null
                ? _buildVerifiedRoomCard(isNarrow)
                : _buildVerificationInputCard(isNarrow),
          ),
        ),
      ),
    );
  }

  // ─── Input & Scanning View ───────────────────────────────────────────────────
  Widget _buildVerificationInputCard(bool isNarrow) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          'Room Verification',
          style: AdminStyles.headingStyle(fontSize: isNarrow ? 20 : 24),
        ),
        const SizedBox(height: 12),
        Text(
          'Enter the room code located on the door, scan the QR code, or upload a photo to quickly start a maintenance request.',
          textAlign: TextAlign.center,
          style: AdminStyles.bodyStyle(
            color: AdminStyles.textSecondary,
            fontSize: isNarrow ? 13 : 14,
          ),
        ),
        const SizedBox(height: 24),

        if (_isScanning)
          Container(
            width: double.infinity,
            height: isNarrow ? 250 : 290,
            constraints: const BoxConstraints(maxWidth: 320),
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: AdminStyles.primary, width: 2),
            ),
            child: Stack(
              children: [
                MobileScanner(
                  onDetect: (capture) {
                    if (_isVerifying) return;
                    final List<Barcode> barcodes = capture.barcodes;
                    for (final barcode in barcodes) {
                      if (barcode.rawValue != null) {
                        setState(() {
                          _codeController.text = barcode.rawValue!;
                        });
                        _verifyRoom();
                        break;
                      }
                    }
                  },
                ),
                Positioned(
                  top: 8,
                  right: 8,
                  child: IconButton(
                    icon: const Icon(Icons.close, color: Colors.white),
                    onPressed: () => setState(() => _isScanning = false),
                    style: IconButton.styleFrom(backgroundColor: Colors.black54),
                  ),
                ),
              ],
            ),
          )
        else
          Column(
            children: [
              InkWell(
                onTap: () => setState(() => _isScanning = true),
                borderRadius: BorderRadius.circular(44),
                child: Container(
                  width: 80,
                  height: 80,
                  decoration: BoxDecoration(
                    color: AdminStyles.primary.withValues(alpha: 0.1),
                    shape: BoxShape.circle,
                  ),
                  child: const Icon(Icons.qr_code_scanner_rounded, color: AdminStyles.primary, size: 40),
                ),
              ),
              const SizedBox(height: 16),
              Wrap(
                alignment: WrapAlignment.center,
                spacing: 12,
                runSpacing: 10,
                children: [
                  ElevatedButton.icon(
                    onPressed: () => setState(() => _isScanning = true),
                    icon: const Icon(Icons.camera_alt_rounded, size: 18),
                    label: const Text('Open Scanner'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AdminStyles.primary.withValues(alpha: 0.1),
                      foregroundColor: AdminStyles.primary,
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                      elevation: 0,
                    ),
                  ),
                  OutlinedButton.icon(
                    onPressed: _isUploading ? null : _uploadAndDecodeQr,
                    icon: _isUploading
                        ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2, color: AdminStyles.primary))
                        : const Icon(Icons.upload_file_rounded, size: 18),
                    label: Text(_isUploading ? 'Scanning File...' : 'Upload QR Code'),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: AdminStyles.primary,
                      side: const BorderSide(color: AdminStyles.primary),
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                    ),
                  ),
                ],
              ),
            ],
          ),

        if (_uploadedImageBytes != null && !_isScanning) ...[
          const SizedBox(height: 20),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: AdminStyles.primary.withValues(alpha: 0.3)),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.04),
                  blurRadius: 8,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Row(
                      children: [
                        const Icon(Icons.qr_code_2_rounded, size: 18, color: AdminStyles.primary),
                        const SizedBox(width: 8),
                        Text(
                          'Uploaded QR Code',
                          style: AdminStyles.bodyStyle(fontSize: 13, fontWeight: FontWeight.bold, color: AdminStyles.textPrimary),
                        ),
                      ],
                    ),
                    InkWell(
                      onTap: () {
                        setState(() {
                          _uploadedImageBytes = null;
                        });
                      },
                      borderRadius: BorderRadius.circular(8),
                      child: const Padding(
                        padding: EdgeInsets.all(4),
                        child: Icon(Icons.close_rounded, size: 16, color: Colors.grey),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                ClipRRect(
                  borderRadius: BorderRadius.circular(10),
                  child: Image.memory(
                    _uploadedImageBytes!,
                    width: 140,
                    height: 140,
                    fit: BoxFit.contain,
                  ),
                ),
              ],
            ),
          ),
        ],

        const SizedBox(height: 28),
        TextField(
          controller: _codeController,
          textCapitalization: TextCapitalization.characters,
          style: AdminStyles.headingStyle(fontSize: 18, letterSpacing: 2),
          textAlign: TextAlign.center,
          decoration: InputDecoration(
            hintText: 'ex. CLR 1',
            hintStyle: AdminStyles.bodyStyle(color: AdminStyles.textMuted, fontSize: 16),
            filled: true,
            fillColor: AdminStyles.bg,
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: AdminStyles.border)),
            enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: AdminStyles.border)),
            focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: AdminStyles.primary, width: 2)),
            errorText: _error,
          ),
          onSubmitted: (_) {
            _codeController.text = _codeController.text.toUpperCase();
            _verifyRoom();
          },
        ),
        const SizedBox(height: 24),
        SizedBox(
          width: double.infinity,
          height: 52,
          child: ElevatedButton(
            onPressed: _isVerifying || _isUploading ? null : () => _verifyRoom(),
            style: ElevatedButton.styleFrom(
              backgroundColor: AdminStyles.primary,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              elevation: 0,
            ),
            child: _isVerifying
                ? const SizedBox(width: 24, height: 24, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                : const Text('Verify Room & Report Issue', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
          ),
        ),
      ],
    );
  }

  // ─── Verified Room View (Matching Mobile RoomVerificationPage) ───────────────
  Widget _buildVerifiedRoomCard(bool isNarrow) {
    final room = _verifiedRoom!;
    final statusColor = _statusColor(room.status);

    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        // Verified Success Icon
        Container(
          width: 64,
          height: 64,
          decoration: BoxDecoration(
            color: const Color(0xFF10B981).withValues(alpha: 0.15),
            shape: BoxShape.circle,
          ),
          child: const Icon(
            Icons.check_circle_rounded,
            size: 38,
            color: Color(0xFF10B981),
          ),
        ),
        const SizedBox(height: 16),
        Text(
          'Location Verified',
          style: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w700,
            color: const Color(0xFF10B981),
            letterSpacing: 0.5,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          room.name,
          textAlign: TextAlign.center,
          style: AdminStyles.headingStyle(fontSize: isNarrow ? 22 : 26),
        ),
        const SizedBox(height: 6),
        Text(
          room.building.isNotEmpty ? room.building : 'Campus Facility',
          textAlign: TextAlign.center,
          style: AdminStyles.bodyStyle(
            color: AdminStyles.textSecondary,
            fontSize: 14,
          ),
        ),
        if (_uploadedImageBytes != null) ...[
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(14),
              border: Border.all(color: const Color(0xFF10B981).withValues(alpha: 0.3)),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.04),
                  blurRadius: 6,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: Column(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: Image.memory(
                    _uploadedImageBytes!,
                    width: 120,
                    height: 120,
                    fit: BoxFit.contain,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Uploaded QR Code',
                  style: AdminStyles.bodyStyle(
                    fontSize: 11,
                    color: const Color(0xFF10B981),
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
          ),
        ],
        const SizedBox(height: 20),

        // Information Tags Card
        Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
          decoration: BoxDecoration(
            color: const Color(0xFFF8FAFC),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: const Color(0xFFE2E8F0)),
          ),
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Facility Type', style: AdminStyles.bodyStyle(color: AdminStyles.textMuted, fontSize: 13)),
                  Text(room.roomType.isNotEmpty ? room.roomType : 'Room', style: AdminStyles.bodyStyle(fontWeight: FontWeight.w600, fontSize: 13)),
                ],
              ),
              if (room.floor.isNotEmpty) ...[
                const Padding(
                  padding: EdgeInsets.symmetric(vertical: 8),
                  child: Divider(height: 1, color: Color(0xFFE2E8F0)),
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text('Floor Level', style: AdminStyles.bodyStyle(color: AdminStyles.textMuted, fontSize: 13)),
                    Text(room.floor, style: AdminStyles.bodyStyle(fontWeight: FontWeight.w600, fontSize: 13)),
                  ],
                ),
              ],
              if (room.department.isNotEmpty) ...[
                const Padding(
                  padding: EdgeInsets.symmetric(vertical: 8),
                  child: Divider(height: 1, color: Color(0xFFE2E8F0)),
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text('Department', style: AdminStyles.bodyStyle(color: AdminStyles.textMuted, fontSize: 13)),
                    Text(room.department, style: AdminStyles.bodyStyle(fontWeight: FontWeight.w600, fontSize: 13)),
                  ],
                ),
              ],
              const Padding(
                padding: EdgeInsets.symmetric(vertical: 8),
                child: Divider(height: 1, color: Color(0xFFE2E8F0)),
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Room Status', style: AdminStyles.bodyStyle(color: AdminStyles.textMuted, fontSize: 13)),
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: BoxDecoration(
                      color: statusColor.withValues(alpha: 0.12),
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Container(width: 6, height: 6, decoration: BoxDecoration(color: statusColor, shape: BoxShape.circle)),
                        const SizedBox(width: 6),
                        Text(
                          room.status.toUpperCase(),
                          style: TextStyle(
                            fontSize: 11,
                            fontWeight: FontWeight.bold,
                            color: statusColor,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),

        const SizedBox(height: 28),

        // Action Buttons
        SizedBox(
          width: double.infinity,
          height: 52,
          child: ElevatedButton.icon(
            onPressed: _proceedToForm,
            icon: const Icon(Icons.warning_amber_rounded, size: 20),
            label: const Text(
              'Proceed to Report Issue',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF00BFA5),
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              elevation: 0,
            ),
          ),
        ),
        const SizedBox(height: 12),
        SizedBox(
          width: double.infinity,
          height: 44,
          child: OutlinedButton(
            onPressed: () {
              setState(() {
                _verifiedRoom = null;
                _codeController.clear();
              });
            },
            style: OutlinedButton.styleFrom(
              foregroundColor: AdminStyles.textSecondary,
              side: const BorderSide(color: Color(0xFFCBD5E1)),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            child: const Text('Change Room / Enter Another'),
          ),
        ),
      ],
    );
  }
}
